version: '3'

services:
  maat:
    image: artifactory.software.geant.org/spa-docker/maat:1.0.6
    hostname: $MAAT_HOST
    ports:
      - "8080:8080"
    environment:
      - MAAT_ROLE_GET_ONLY=$MAAT_ROLE_GET_ONLY
      - MAAT_ROLE_POST_ONLY=$MAAT_ROLE_POST_ONLY
      - MAAT_ROLE_DELETE_ONLY=$MAAT_ROLE_DELETE_ONLY
      - MAAT_ROLE_PATCH_ONLY=$MAAT_ROLE_PATCH_ONLY
      - KEYCLOAK_ENABLED=$KEYCLOAK_ENABLED
      - KEYCLOAK_HOST=$KEYCLOAK_HOST
      - KEYCLOAK_PORT=$KEYCLOAK_PORT
      - KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
      - KEYCLOAK_AUTHORIZATION_L1_ROLES=$KEYCLOAK_AUTHORIZATION_L1_ROLES
      - KEYCLOAK_AUTHORIZATION_L2_FILTERS=$KEYCLOAK_AUTHORIZATION_L2_FILTERS
      - server.ssl.enabled=false
      - MONGO_HOST=$MONGODB_HOST
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MAAT_PORT=$MAAT_PORT
      - MAAT_RESOURCE_PROTOCOL=$MAAT_RESOURCE_PROTOCOL
      - MAAT_RESOURCE_ADDRESS=$MAAT_RESOURCE_ADDRESS
      - MAAT_RESOURCE_PORT=$MAAT_RESOURCE_PORT
      - MAAT_SERVICE_PROTOCOL=$MAAT_SERVICE_PROTOCOL
      - MAAT_SERVICE_ADDRESS=$MAAT_SERVICE_ADDRESS
      - MAAT_SERVICE_PORT=$MAAT_SERVICE_PORT
      - GRAYLOG_HOST=$GRAYLOG_HOST
      - GRAYLOG_PORT=$GRAYLOG_PORT
      - LOGGING_CONFIG=$LOGGING_CONFIG

  mongodb:
    image: mongo:7.0.4
    hostname: $MONGODB_HOST
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD

volumes:
  mongodb: