version: '3'

services:
  maat:
    image: artifactory.software.geant.org/spa-docker/maat:1.0.8
    hostname: $MAAT_HOST
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ENABLED=false
      - KEYCLOAK_AUTHORIZATION_L1_ROLES=false
      - KEYCLOAK_AUTHORIZATION_L2_FILTERS=false
      - server.ssl.enabled=false
      - MONGO_HOST=$MONGODB_HOST
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MAAT_PORT=$MAAT_PORT
      - MAAT_RESOURCE_PROTOCOL=$MAAT_RESOURCE_PROTOCOL
      - MAAT_RESOURCE_ADDRESS=$MAAT_RESOURCE_ADDRESS
      - MAAT_RESOURCE_PORT=$MAAT_RESOURCE_PORT
      - MAAT_SERVICE_PROTOCOL=$MAAT_SERVICE_PROTOCOL
      - MAAT_SERVICE_ADDRESS=$MAAT_SERVICE_ADDRESS
      - MAAT_SERVICE_PORT=$MAAT_SERVICE_PORT
      - LOGGING_CONFIG=classpath:logback-with-file-and-console-without-graylog.xml
    depends_on:
      mongodb-maat:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080 --server-response 2>&1 | grep -E \"(401|200)\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10

  mongodb-maat:
    image: mongo:7.0.4
    hostname: $MONGODB_HOST
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb-maat:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  mongodb-maat: