server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # Loki Adress

scrape_configs:
  - job_name: "docker-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"

    pipeline_stages:

      - json:
          expressions:
            level: level

      - replace:
          source: level
          expression: "^$"
          replace: "UNKNOWN"


